### ISSUE TITLE
Add mode to reject conflicting changes in model-server

### ISSUE THREAD

**Issue by languitar** [modelix/modelix.core#4]
Clients applications of the model-server might have to inform users about things like lost updates. The model-server must make it possible for them to detect such situations.

**Comment by nkoester** [comment]
Conceptually no change is lost when updates are sent as the model server merges/migrates each atomic change. Thus no rejections happen as they are immediately resolved. The history retains the merge operation so that this "conflict" can be inspected and no data is lost. Model validity additionally shall be computed somewhere else.
